### PR TITLE
Improvements in README.md and CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by bhaskarmac**
Adding few Github badges to README.md, content improvements in README and CONTRIBUTING file. Please check and accept the Pull request.

### CODE REVIEW

**Comment by Leocardoso94** [comment]
Wow! Looks awesome. Thanks for your time @bhaskarmac !

**Comment by Leocardoso94** [comment]
#60

**Comment by bhaskarmac** [comment]
Welcome, @Leocardoso94  I will keep contributing to this repo because I find it interesting and other folks also should get the benefit out of this. We should cover all possible free learning content for devs.

**Comment by Leocardoso94** [comment]
Awesome! An average of 200 people a day look at the site. Certainly we are helping some devs

**Comment by bhaskarmac** [comment]
That's great 👍  I have also shared the site with all of my friends.

**Pull request merged**
